try {
  let resultado = 10 / 0;
  console.log(resultado);
} catch (erro) {
  console.log("Erro:", erro.message);
}